#ifndef DRA_LOOPS_ARGS_H
#define DRA_LOOPS_ARGS_H
#define DRA_EXPAND(x) x
#define FOR_EACH_DO_1(fn,x) fn(x)
#define FOR_EACH_DO_2(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_1(fn,__VA_ARGS__))
#define FOR_EACH_DO_3(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_2(fn,__VA_ARGS__))
#define FOR_EACH_DO_4(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_3(fn,__VA_ARGS__))
#define FOR_EACH_DO_5(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_4(fn,__VA_ARGS__))
#define FOR_EACH_DO_6(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_5(fn,__VA_ARGS__))
#define FOR_EACH_DO_7(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_6(fn,__VA_ARGS__))
#define FOR_EACH_DO_8(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_7(fn,__VA_ARGS__))
#define FOR_EACH_DO_9(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_8(fn,__VA_ARGS__))
#define FOR_EACH_DO_10(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_9(fn,__VA_ARGS__))
#define FOR_EACH_DO_11(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_10(fn,__VA_ARGS__))
#define FOR_EACH_DO_12(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_11(fn,__VA_ARGS__))
#define FOR_EACH_DO_13(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_12(fn,__VA_ARGS__))
#define FOR_EACH_DO_14(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_13(fn,__VA_ARGS__))
#define FOR_EACH_DO_15(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_14(fn,__VA_ARGS__))
#define FOR_EACH_DO_16(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_15(fn,__VA_ARGS__))
#define FOR_EACH_DO_17(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_16(fn,__VA_ARGS__))
#define FOR_EACH_DO_18(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_17(fn,__VA_ARGS__))
#define FOR_EACH_DO_19(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_18(fn,__VA_ARGS__))
#define FOR_EACH_DO_20(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_19(fn,__VA_ARGS__))
#define FOR_EACH_DO_21(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_20(fn,__VA_ARGS__))
#define FOR_EACH_DO_22(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_21(fn,__VA_ARGS__))
#define FOR_EACH_DO_23(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_22(fn,__VA_ARGS__))
#define FOR_EACH_DO_24(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_23(fn,__VA_ARGS__))
#define FOR_EACH_DO_25(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_24(fn,__VA_ARGS__))
#define FOR_EACH_DO_26(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_25(fn,__VA_ARGS__))
#define FOR_EACH_DO_27(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_26(fn,__VA_ARGS__))
#define FOR_EACH_DO_28(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_27(fn,__VA_ARGS__))
#define FOR_EACH_DO_29(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_28(fn,__VA_ARGS__))
#define FOR_EACH_DO_30(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_29(fn,__VA_ARGS__))
#define FOR_EACH_DO_31(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_30(fn,__VA_ARGS__))
#define FOR_EACH_DO_32(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_31(fn,__VA_ARGS__))
#define FOR_EACH_DO_33(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_32(fn,__VA_ARGS__))
#define FOR_EACH_DO_34(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_33(fn,__VA_ARGS__))
#define FOR_EACH_DO_35(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_34(fn,__VA_ARGS__))
#define FOR_EACH_DO_36(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_35(fn,__VA_ARGS__))
#define FOR_EACH_DO_37(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_36(fn,__VA_ARGS__))
#define FOR_EACH_DO_38(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_37(fn,__VA_ARGS__))
#define FOR_EACH_DO_39(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_38(fn,__VA_ARGS__))
#define FOR_EACH_DO_40(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_39(fn,__VA_ARGS__))
#define FOR_EACH_DO_41(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_40(fn,__VA_ARGS__))
#define FOR_EACH_DO_42(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_41(fn,__VA_ARGS__))
#define FOR_EACH_DO_43(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_42(fn,__VA_ARGS__))
#define FOR_EACH_DO_44(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_43(fn,__VA_ARGS__))
#define FOR_EACH_DO_45(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_44(fn,__VA_ARGS__))
#define FOR_EACH_DO_46(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_45(fn,__VA_ARGS__))
#define FOR_EACH_DO_47(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_46(fn,__VA_ARGS__))
#define FOR_EACH_DO_48(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_47(fn,__VA_ARGS__))
#define FOR_EACH_DO_49(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_48(fn,__VA_ARGS__))
#define FOR_EACH_DO_50(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_49(fn,__VA_ARGS__))
#define FOR_EACH_DO_51(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_50(fn,__VA_ARGS__))
#define FOR_EACH_DO_52(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_51(fn,__VA_ARGS__))
#define FOR_EACH_DO_53(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_52(fn,__VA_ARGS__))
#define FOR_EACH_DO_54(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_53(fn,__VA_ARGS__))
#define FOR_EACH_DO_55(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_54(fn,__VA_ARGS__))
#define FOR_EACH_DO_56(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_55(fn,__VA_ARGS__))
#define FOR_EACH_DO_57(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_56(fn,__VA_ARGS__))
#define FOR_EACH_DO_58(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_57(fn,__VA_ARGS__))
#define FOR_EACH_DO_59(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_58(fn,__VA_ARGS__))
#define FOR_EACH_DO_60(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_59(fn,__VA_ARGS__))
#define FOR_EACH_DO_61(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_60(fn,__VA_ARGS__))
#define FOR_EACH_DO_62(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_61(fn,__VA_ARGS__))
#define FOR_EACH_DO_63(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_62(fn,__VA_ARGS__))
#define FOR_EACH_DO_64(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_63(fn,__VA_ARGS__))
#define FOR_EACH_DO_65(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_64(fn,__VA_ARGS__))
#define FOR_EACH_DO_66(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_65(fn,__VA_ARGS__))
#define FOR_EACH_DO_67(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_66(fn,__VA_ARGS__))
#define FOR_EACH_DO_68(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_67(fn,__VA_ARGS__))
#define FOR_EACH_DO_69(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_68(fn,__VA_ARGS__))
#define FOR_EACH_DO_70(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_69(fn,__VA_ARGS__))
#define FOR_EACH_DO_71(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_70(fn,__VA_ARGS__))
#define FOR_EACH_DO_72(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_71(fn,__VA_ARGS__))
#define FOR_EACH_DO_73(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_72(fn,__VA_ARGS__))
#define FOR_EACH_DO_74(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_73(fn,__VA_ARGS__))
#define FOR_EACH_DO_75(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_74(fn,__VA_ARGS__))
#define FOR_EACH_DO_76(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_75(fn,__VA_ARGS__))
#define FOR_EACH_DO_77(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_76(fn,__VA_ARGS__))
#define FOR_EACH_DO_78(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_77(fn,__VA_ARGS__))
#define FOR_EACH_DO_79(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_78(fn,__VA_ARGS__))
#define FOR_EACH_DO_80(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_79(fn,__VA_ARGS__))
#define FOR_EACH_DO_81(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_80(fn,__VA_ARGS__))
#define FOR_EACH_DO_82(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_81(fn,__VA_ARGS__))
#define FOR_EACH_DO_83(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_82(fn,__VA_ARGS__))
#define FOR_EACH_DO_84(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_83(fn,__VA_ARGS__))
#define FOR_EACH_DO_85(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_84(fn,__VA_ARGS__))
#define FOR_EACH_DO_86(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_85(fn,__VA_ARGS__))
#define FOR_EACH_DO_87(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_86(fn,__VA_ARGS__))
#define FOR_EACH_DO_88(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_87(fn,__VA_ARGS__))
#define FOR_EACH_DO_89(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_88(fn,__VA_ARGS__))
#define FOR_EACH_DO_90(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_89(fn,__VA_ARGS__))
#define FOR_EACH_DO_91(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_90(fn,__VA_ARGS__))
#define FOR_EACH_DO_92(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_91(fn,__VA_ARGS__))
#define FOR_EACH_DO_93(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_92(fn,__VA_ARGS__))
#define FOR_EACH_DO_94(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_93(fn,__VA_ARGS__))
#define FOR_EACH_DO_95(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_94(fn,__VA_ARGS__))
#define FOR_EACH_DO_96(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_95(fn,__VA_ARGS__))
#define FOR_EACH_DO_97(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_96(fn,__VA_ARGS__))
#define FOR_EACH_DO_98(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_97(fn,__VA_ARGS__))
#define FOR_EACH_DO_99(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_98(fn,__VA_ARGS__))
#define FOR_EACH_DO_100(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_99(fn,__VA_ARGS__))
#define FOR_EACH_DO(fn,...) DRA_EXPAND(COUNT_NUM_ARGS_FN_CALL(FOR_EACH_DO,__VA_ARGS__) (fn,__VA_ARGS__))
#define FOR_EACH_GET_1(fn,x) fn(x)
#define FOR_EACH_GET_2(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_1(fn,__VA_ARGS__))
#define FOR_EACH_GET_3(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_2(fn,__VA_ARGS__))
#define FOR_EACH_GET_4(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_3(fn,__VA_ARGS__))
#define FOR_EACH_GET_5(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_4(fn,__VA_ARGS__))
#define FOR_EACH_GET_6(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_5(fn,__VA_ARGS__))
#define FOR_EACH_GET_7(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_6(fn,__VA_ARGS__))
#define FOR_EACH_GET_8(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_7(fn,__VA_ARGS__))
#define FOR_EACH_GET_9(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_8(fn,__VA_ARGS__))
#define FOR_EACH_GET_10(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_9(fn,__VA_ARGS__))
#define FOR_EACH_GET_11(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_10(fn,__VA_ARGS__))
#define FOR_EACH_GET_12(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_11(fn,__VA_ARGS__))
#define FOR_EACH_GET_13(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_12(fn,__VA_ARGS__))
#define FOR_EACH_GET_14(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_13(fn,__VA_ARGS__))
#define FOR_EACH_GET_15(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_14(fn,__VA_ARGS__))
#define FOR_EACH_GET_16(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_15(fn,__VA_ARGS__))
#define FOR_EACH_GET_17(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_16(fn,__VA_ARGS__))
#define FOR_EACH_GET_18(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_17(fn,__VA_ARGS__))
#define FOR_EACH_GET_19(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_18(fn,__VA_ARGS__))
#define FOR_EACH_GET_20(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_19(fn,__VA_ARGS__))
#define FOR_EACH_GET_21(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_20(fn,__VA_ARGS__))
#define FOR_EACH_GET_22(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_21(fn,__VA_ARGS__))
#define FOR_EACH_GET_23(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_22(fn,__VA_ARGS__))
#define FOR_EACH_GET_24(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_23(fn,__VA_ARGS__))
#define FOR_EACH_GET_25(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_24(fn,__VA_ARGS__))
#define FOR_EACH_GET_26(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_25(fn,__VA_ARGS__))
#define FOR_EACH_GET_27(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_26(fn,__VA_ARGS__))
#define FOR_EACH_GET_28(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_27(fn,__VA_ARGS__))
#define FOR_EACH_GET_29(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_28(fn,__VA_ARGS__))
#define FOR_EACH_GET_30(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_29(fn,__VA_ARGS__))
#define FOR_EACH_GET_31(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_30(fn,__VA_ARGS__))
#define FOR_EACH_GET_32(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_31(fn,__VA_ARGS__))
#define FOR_EACH_GET_33(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_32(fn,__VA_ARGS__))
#define FOR_EACH_GET_34(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_33(fn,__VA_ARGS__))
#define FOR_EACH_GET_35(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_34(fn,__VA_ARGS__))
#define FOR_EACH_GET_36(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_35(fn,__VA_ARGS__))
#define FOR_EACH_GET_37(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_36(fn,__VA_ARGS__))
#define FOR_EACH_GET_38(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_37(fn,__VA_ARGS__))
#define FOR_EACH_GET_39(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_38(fn,__VA_ARGS__))
#define FOR_EACH_GET_40(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_39(fn,__VA_ARGS__))
#define FOR_EACH_GET_41(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_40(fn,__VA_ARGS__))
#define FOR_EACH_GET_42(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_41(fn,__VA_ARGS__))
#define FOR_EACH_GET_43(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_42(fn,__VA_ARGS__))
#define FOR_EACH_GET_44(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_43(fn,__VA_ARGS__))
#define FOR_EACH_GET_45(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_44(fn,__VA_ARGS__))
#define FOR_EACH_GET_46(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_45(fn,__VA_ARGS__))
#define FOR_EACH_GET_47(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_46(fn,__VA_ARGS__))
#define FOR_EACH_GET_48(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_47(fn,__VA_ARGS__))
#define FOR_EACH_GET_49(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_48(fn,__VA_ARGS__))
#define FOR_EACH_GET_50(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_49(fn,__VA_ARGS__))
#define FOR_EACH_GET_51(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_50(fn,__VA_ARGS__))
#define FOR_EACH_GET_52(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_51(fn,__VA_ARGS__))
#define FOR_EACH_GET_53(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_52(fn,__VA_ARGS__))
#define FOR_EACH_GET_54(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_53(fn,__VA_ARGS__))
#define FOR_EACH_GET_55(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_54(fn,__VA_ARGS__))
#define FOR_EACH_GET_56(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_55(fn,__VA_ARGS__))
#define FOR_EACH_GET_57(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_56(fn,__VA_ARGS__))
#define FOR_EACH_GET_58(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_57(fn,__VA_ARGS__))
#define FOR_EACH_GET_59(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_58(fn,__VA_ARGS__))
#define FOR_EACH_GET_60(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_59(fn,__VA_ARGS__))
#define FOR_EACH_GET_61(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_60(fn,__VA_ARGS__))
#define FOR_EACH_GET_62(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_61(fn,__VA_ARGS__))
#define FOR_EACH_GET_63(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_62(fn,__VA_ARGS__))
#define FOR_EACH_GET_64(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_63(fn,__VA_ARGS__))
#define FOR_EACH_GET_65(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_64(fn,__VA_ARGS__))
#define FOR_EACH_GET_66(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_65(fn,__VA_ARGS__))
#define FOR_EACH_GET_67(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_66(fn,__VA_ARGS__))
#define FOR_EACH_GET_68(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_67(fn,__VA_ARGS__))
#define FOR_EACH_GET_69(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_68(fn,__VA_ARGS__))
#define FOR_EACH_GET_70(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_69(fn,__VA_ARGS__))
#define FOR_EACH_GET_71(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_70(fn,__VA_ARGS__))
#define FOR_EACH_GET_72(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_71(fn,__VA_ARGS__))
#define FOR_EACH_GET_73(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_72(fn,__VA_ARGS__))
#define FOR_EACH_GET_74(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_73(fn,__VA_ARGS__))
#define FOR_EACH_GET_75(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_74(fn,__VA_ARGS__))
#define FOR_EACH_GET_76(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_75(fn,__VA_ARGS__))
#define FOR_EACH_GET_77(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_76(fn,__VA_ARGS__))
#define FOR_EACH_GET_78(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_77(fn,__VA_ARGS__))
#define FOR_EACH_GET_79(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_78(fn,__VA_ARGS__))
#define FOR_EACH_GET_80(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_79(fn,__VA_ARGS__))
#define FOR_EACH_GET_81(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_80(fn,__VA_ARGS__))
#define FOR_EACH_GET_82(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_81(fn,__VA_ARGS__))
#define FOR_EACH_GET_83(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_82(fn,__VA_ARGS__))
#define FOR_EACH_GET_84(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_83(fn,__VA_ARGS__))
#define FOR_EACH_GET_85(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_84(fn,__VA_ARGS__))
#define FOR_EACH_GET_86(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_85(fn,__VA_ARGS__))
#define FOR_EACH_GET_87(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_86(fn,__VA_ARGS__))
#define FOR_EACH_GET_88(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_87(fn,__VA_ARGS__))
#define FOR_EACH_GET_89(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_88(fn,__VA_ARGS__))
#define FOR_EACH_GET_90(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_89(fn,__VA_ARGS__))
#define FOR_EACH_GET_91(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_90(fn,__VA_ARGS__))
#define FOR_EACH_GET_92(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_91(fn,__VA_ARGS__))
#define FOR_EACH_GET_93(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_92(fn,__VA_ARGS__))
#define FOR_EACH_GET_94(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_93(fn,__VA_ARGS__))
#define FOR_EACH_GET_95(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_94(fn,__VA_ARGS__))
#define FOR_EACH_GET_96(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_95(fn,__VA_ARGS__))
#define FOR_EACH_GET_97(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_96(fn,__VA_ARGS__))
#define FOR_EACH_GET_98(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_97(fn,__VA_ARGS__))
#define FOR_EACH_GET_99(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_98(fn,__VA_ARGS__))
#define FOR_EACH_GET_100(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_99(fn,__VA_ARGS__))
#define FOR_EACH_GET(fn,...) DRA_EXPAND(COUNT_NUM_ARGS_FN_CALL(FOR_EACH_GET,__VA_ARGS__) (fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_1(fn,x) fn(x)
#define FOR_EACH_ENUMERATE_2(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_1(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_3(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_2(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_4(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_3(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_5(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_4(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_6(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_5(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_7(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_6(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_8(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_7(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_9(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_8(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_10(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_9(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_11(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_10(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_12(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_11(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_13(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_12(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_14(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_13(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_15(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_14(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_16(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_15(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_17(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_16(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_18(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_17(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_19(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_18(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_20(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_19(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_21(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_20(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_22(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_21(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_23(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_22(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_24(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_23(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_25(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_24(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_26(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_25(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_27(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_26(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_28(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_27(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_29(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_28(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_30(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_29(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_31(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_30(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_32(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_31(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_33(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_32(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_34(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_33(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_35(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_34(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_36(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_35(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_37(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_36(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_38(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_37(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_39(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_38(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_40(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_39(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_41(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_40(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_42(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_41(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_43(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_42(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_44(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_43(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_45(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_44(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_46(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_45(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_47(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_46(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_48(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_47(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_49(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_48(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_50(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_49(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_51(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_50(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_52(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_51(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_53(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_52(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_54(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_53(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_55(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_54(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_56(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_55(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_57(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_56(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_58(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_57(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_59(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_58(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_60(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_59(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_61(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_60(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_62(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_61(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_63(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_62(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_64(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_63(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_65(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_64(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_66(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_65(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_67(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_66(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_68(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_67(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_69(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_68(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_70(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_69(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_71(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_70(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_72(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_71(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_73(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_72(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_74(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_73(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_75(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_74(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_76(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_75(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_77(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_76(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_78(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_77(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_79(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_78(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_80(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_79(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_81(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_80(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_82(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_81(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_83(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_82(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_84(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_83(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_85(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_84(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_86(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_85(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_87(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_86(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_88(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_87(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_89(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_88(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_90(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_89(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_91(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_90(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_92(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_91(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_93(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_92(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_94(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_93(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_95(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_94(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_96(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_95(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_97(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_96(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_98(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_97(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_99(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_98(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_100(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_99(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE(fn,...) DRA_EXPAND(COUNT_NUM_ARGS_FN_CALL(FOR_EACH_ENUMERATE,__VA_ARGS__) (fn,__VA_ARGS__))
#define COUNT_NUM_ARGS_IMPL(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67,_68,_69,_70,_71,_72,_73,_74,_75,_76,_77,_78,_79,_80,_81,_82,_83,_84,_85,_86,_87,_88,_89,_90,_91,_92,_93,_94,_95,_96,_97,_98,_99,_100,N,...) N
#define COUNT_NUM_ARGS(...) COUNT_NUM_ARGS_IMPL(__VA_ARGS__,100,99,98,97,96,95,94,93,92,91,90,89,88,87,86,85,84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0)
#define COUNT_NUM_ARGS_FN_CALL(func_name,...) DRA_EXPAND(COUNT_NUM_ARGS_IMPL(__VA_ARGS__,func_name##_100,func_name##_99,func_name##_98,func_name##_97,func_name##_96,func_name##_95,func_name##_94,func_name##_93,func_name##_92,func_name##_91,func_name##_90,func_name##_89,func_name##_88,func_name##_87,func_name##_86,func_name##_85,func_name##_84,func_name##_83,func_name##_82,func_name##_81,func_name##_80,func_name##_79,func_name##_78,func_name##_77,func_name##_76,func_name##_75,func_name##_74,func_name##_73,func_name##_72,func_name##_71,func_name##_70,func_name##_69,func_name##_68,func_name##_67,func_name##_66,func_name##_65,func_name##_64,func_name##_63,func_name##_62,func_name##_61,func_name##_60,func_name##_59,func_name##_58,func_name##_57,func_name##_56,func_name##_55,func_name##_54,func_name##_53,func_name##_52,func_name##_51,func_name##_50,func_name##_49,func_name##_48,func_name##_47,func_name##_46,func_name##_45,func_name##_44,func_name##_43,func_name##_42,func_name##_41,func_name##_40,func_name##_39,func_name##_38,func_name##_37,func_name##_36,func_name##_35,func_name##_34,func_name##_33,func_name##_32,func_name##_31,func_name##_30,func_name##_29,func_name##_28,func_name##_27,func_name##_26,func_name##_25,func_name##_24,func_name##_23,func_name##_22,func_name##_21,func_name##_20,func_name##_19,func_name##_18,func_name##_17,func_name##_16,func_name##_15,func_name##_14,func_name##_13,func_name##_12,func_name##_11,func_name##_10,func_name##_9,func_name##_8,func_name##_7,func_name##_6,func_name##_5,func_name##_4,func_name##_3,func_name##_2,func_name##_1,func_name##_0))
#endif
