#ifndef DRA_LOOPS_ARGS_H
#define DRA_LOOPS_ARGS_H
#define DRA_EXPAND(x) x
#define FOR_EACH_DO_1(fn,x) fn(x)
#define FOR_EACH_DO_2(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_1(fn,__VA_ARGS__))
#define FOR_EACH_DO_3(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_2(fn,__VA_ARGS__))
#define FOR_EACH_DO_4(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_3(fn,__VA_ARGS__))
#define FOR_EACH_DO_5(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_4(fn,__VA_ARGS__))
#define FOR_EACH_DO_6(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_5(fn,__VA_ARGS__))
#define FOR_EACH_DO_7(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_6(fn,__VA_ARGS__))
#define FOR_EACH_DO_8(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_7(fn,__VA_ARGS__))
#define FOR_EACH_DO_9(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_8(fn,__VA_ARGS__))
#define FOR_EACH_DO_10(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_9(fn,__VA_ARGS__))
#define FOR_EACH_DO_11(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_10(fn,__VA_ARGS__))
#define FOR_EACH_DO_12(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_11(fn,__VA_ARGS__))
#define FOR_EACH_DO_13(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_12(fn,__VA_ARGS__))
#define FOR_EACH_DO_14(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_13(fn,__VA_ARGS__))
#define FOR_EACH_DO_15(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_14(fn,__VA_ARGS__))
#define FOR_EACH_DO_16(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_15(fn,__VA_ARGS__))
#define FOR_EACH_DO_17(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_16(fn,__VA_ARGS__))
#define FOR_EACH_DO_18(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_17(fn,__VA_ARGS__))
#define FOR_EACH_DO_19(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_18(fn,__VA_ARGS__))
#define FOR_EACH_DO_20(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_19(fn,__VA_ARGS__))
#define FOR_EACH_DO_21(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_20(fn,__VA_ARGS__))
#define FOR_EACH_DO_22(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_21(fn,__VA_ARGS__))
#define FOR_EACH_DO_23(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_22(fn,__VA_ARGS__))
#define FOR_EACH_DO_24(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_23(fn,__VA_ARGS__))
#define FOR_EACH_DO_25(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_24(fn,__VA_ARGS__))
#define FOR_EACH_DO_26(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_25(fn,__VA_ARGS__))
#define FOR_EACH_DO_27(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_26(fn,__VA_ARGS__))
#define FOR_EACH_DO_28(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_27(fn,__VA_ARGS__))
#define FOR_EACH_DO_29(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_28(fn,__VA_ARGS__))
#define FOR_EACH_DO_30(fn,x,...) fn(x); DRA_EXPAND(FOR_EACH_DO_29(fn,__VA_ARGS__))
#define FOR_EACH_DO(fn,...) DRA_EXPAND(COUNT_NUM_ARGS_FN_CALL(FOR_EACH_DO,__VA_ARGS__) (fn,__VA_ARGS__))
#define FOR_EACH_GET_1(fn,x) fn(x)
#define FOR_EACH_GET_2(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_1(fn,__VA_ARGS__))
#define FOR_EACH_GET_3(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_2(fn,__VA_ARGS__))
#define FOR_EACH_GET_4(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_3(fn,__VA_ARGS__))
#define FOR_EACH_GET_5(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_4(fn,__VA_ARGS__))
#define FOR_EACH_GET_6(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_5(fn,__VA_ARGS__))
#define FOR_EACH_GET_7(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_6(fn,__VA_ARGS__))
#define FOR_EACH_GET_8(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_7(fn,__VA_ARGS__))
#define FOR_EACH_GET_9(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_8(fn,__VA_ARGS__))
#define FOR_EACH_GET_10(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_9(fn,__VA_ARGS__))
#define FOR_EACH_GET_11(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_10(fn,__VA_ARGS__))
#define FOR_EACH_GET_12(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_11(fn,__VA_ARGS__))
#define FOR_EACH_GET_13(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_12(fn,__VA_ARGS__))
#define FOR_EACH_GET_14(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_13(fn,__VA_ARGS__))
#define FOR_EACH_GET_15(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_14(fn,__VA_ARGS__))
#define FOR_EACH_GET_16(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_15(fn,__VA_ARGS__))
#define FOR_EACH_GET_17(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_16(fn,__VA_ARGS__))
#define FOR_EACH_GET_18(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_17(fn,__VA_ARGS__))
#define FOR_EACH_GET_19(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_18(fn,__VA_ARGS__))
#define FOR_EACH_GET_20(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_19(fn,__VA_ARGS__))
#define FOR_EACH_GET_21(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_20(fn,__VA_ARGS__))
#define FOR_EACH_GET_22(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_21(fn,__VA_ARGS__))
#define FOR_EACH_GET_23(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_22(fn,__VA_ARGS__))
#define FOR_EACH_GET_24(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_23(fn,__VA_ARGS__))
#define FOR_EACH_GET_25(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_24(fn,__VA_ARGS__))
#define FOR_EACH_GET_26(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_25(fn,__VA_ARGS__))
#define FOR_EACH_GET_27(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_26(fn,__VA_ARGS__))
#define FOR_EACH_GET_28(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_27(fn,__VA_ARGS__))
#define FOR_EACH_GET_29(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_28(fn,__VA_ARGS__))
#define FOR_EACH_GET_30(fn,x,...) fn(x) DRA_EXPAND(FOR_EACH_GET_29(fn,__VA_ARGS__))
#define FOR_EACH_GET(fn,...) DRA_EXPAND(COUNT_NUM_ARGS_FN_CALL(FOR_EACH_GET,__VA_ARGS__) (fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_1(fn,x) fn(x)
#define FOR_EACH_ENUMERATE_2(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_1(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_3(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_2(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_4(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_3(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_5(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_4(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_6(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_5(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_7(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_6(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_8(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_7(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_9(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_8(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_10(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_9(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_11(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_10(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_12(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_11(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_13(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_12(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_14(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_13(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_15(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_14(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_16(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_15(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_17(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_16(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_18(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_17(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_19(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_18(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_20(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_19(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_21(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_20(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_22(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_21(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_23(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_22(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_24(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_23(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_25(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_24(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_26(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_25(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_27(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_26(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_28(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_27(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_29(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_28(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE_30(fn,x,...) fn(x) , DRA_EXPAND(FOR_EACH_ENUMERATE_29(fn,__VA_ARGS__))
#define FOR_EACH_ENUMERATE(fn,...) DRA_EXPAND(COUNT_NUM_ARGS_FN_CALL(FOR_EACH_ENUMERATE,__VA_ARGS__) (fn,__VA_ARGS__))
#define COUNT_NUM_ARGS_IMPL(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,N,...) N
#define COUNT_NUM_ARGS(...) COUNT_NUM_ARGS_IMPL(__VA_ARGS__,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0)
#define COUNT_NUM_ARGS_FN_CALL(func_name,...) DRA_EXPAND(COUNT_NUM_ARGS_IMPL(__VA_ARGS__,func_name##_30,func_name##_29,func_name##_28,func_name##_27,func_name##_26,func_name##_25,func_name##_24,func_name##_23,func_name##_22,func_name##_21,func_name##_20,func_name##_19,func_name##_18,func_name##_17,func_name##_16,func_name##_15,func_name##_14,func_name##_13,func_name##_12,func_name##_11,func_name##_10,func_name##_9,func_name##_8,func_name##_7,func_name##_6,func_name##_5,func_name##_4,func_name##_3,func_name##_2,func_name##_1,func_name##_0))
#endif
